[package]
name = "naifspice-sys"
version = "0.1.0"
edition = "2021"
links = "cspice"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1.0.73"
sha2 = "0.10.2"
ureq = "2.4.0"
tar = "0.4.38"